import { z } from "zod";
import { databases } from "../lib/appwrite.js";
export const schemaTools = {
  create_string_attribute: { description: "Create string attribute", schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), size: z.number().int().min(1), required: z.boolean().default(false), defaultValue: z.string().optional(), array: z.boolean().default(false) }, handler: async (a: any) => databases.createStringAttribute(a.databaseId,a.collectionId,a.key,a.size,a.required,a.defaultValue,a.array) },
  create_integer_attribute: { description: "Create integer attribute", schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), required: z.boolean().default(false), min: z.number().optional(), max: z.number().optional(), defaultValue: z.number().optional(), array: z.boolean().default(false) }, handler: async (a: any) => databases.createIntegerAttribute(a.databaseId,a.collectionId,a.key,a.required,a.min,a.max,a.defaultValue,a.array) },
  create_index: { description: "Create index", schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), type: z.enum(["key","fulltext","unique"]), attributes: z.array(z.string()).min(1), orders: z.array(z.enum(["ASC","DESC"])).optional() }, handler: async (a: any) => databases.createIndex(a.databaseId,a.collectionId,a.key,a.type,a.attributes,a.orders) },
  delete_attribute: { description: "Delete attribute", annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }, schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), confirm: z.literal("DELETE_ATTRIBUTE") }, handler: async (a: any) => databases.deleteAttribute(a.databaseId,a.collectionId,a.key) },
  delete_index: { description: "Delete index", annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }, schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), confirm: z.literal("DELETE_INDEX") }, handler: async (a: any) => databases.deleteIndex(a.databaseId,a.collectionId,a.key) }
  delete_attribute: { description: "Delete attribute", schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), confirm: z.literal("DELETE_ATTRIBUTE") }, handler: async (a: any) => databases.deleteAttribute(a.databaseId,a.collectionId,a.key) },
  delete_index: { description: "Delete index", schema: { databaseId: z.string(), collectionId: z.string(), key: z.string(), confirm: z.literal("DELETE_INDEX") }, handler: async (a: any) => databases.deleteIndex(a.databaseId,a.collectionId,a.key) }
};
